### ISSUE TITLE
[JS] dev, devDependencies, peerDependencies

### ISSUE THREAD

**Issue by phuocng** [phuocng/this-vs-that#137]

**Comment by YerinAlexey** [comment]
`dependencies`:
 - Always implicitly installed in dependent package

`devDependencies`:
 - Not installed in dependent package.
 - Used for development-specific things like test runners or preprocessors
 - Installed by default when running `npm install` (or `yarn install`) in library folder, can be disabled with `--production` flag

`peerDependencies`: External packages those should be installed alongside with the library. For example, when I put `react` in my `peerDependencies`, it won't install anything, but package manager will warn user that `react` should be installed in dependent package

p.s. by "library" I mean package that should be installed (`react`, for example)
