### ISSUE TITLE
[React] React.createElement() vs JSX

### ISSUE THREAD

**Issue by phuocng** [phuocng/this-vs-that#282]

**Comment by MkDev11** [comment]
'React.createElement()' and JSX are two ways of defining and creating React elements in a React application. They serve the same purpose but offer different syntax and readability. Here's a comparison of the two approaches:

**1. 'React.createElement()':**
   
   'React.createElement()' is the foundational method provided by React to create React elements. It takes three arguments: the type of element (such as a component or HTML tag), an optional object of properties (props), and the element's children.

   Example using 'React.createElement()':
   
   const element = React.createElement('div', { className: 'container' }, 'Hello, World!');
   
   In this example, 'element' represents a React element, which can be rendered to the DOM using 'ReactDOM.render()'.

**2. JSX:**

   JSX is a syntax extension for JavaScript that allows you to write HTML-like code directly within your JavaScript files. JSX is transformed into 'React.createElement()' calls by build tools like Babel before it's executed in the browser.

   Example using JSX:

    const element = <div className="container">Hello, World!</div>;
   
   JSX code appears more like HTML, which can make it easier to read and write, especially for complex UI structures. Under the hood, this JSX code gets compiled to the equivalent 'React.createElement()' code.

***Key Differences:***

- *Syntax:* JSX resembles HTML, making it more readable and familiar to developers, while 'React.createElement()' uses a function call syntax.

- *Complexity:* For more complex and nested structures, JSX tends to be more concise and easier to work with. It reduces the verbosity of 'React.createElement()'.

- *Tooling:* JSX requires transpilation using tools like Babel, whereas 'React.createElement()' can be used without JSX and transpilation.

**Comment by DonMiller9294** [comment]
Hello thank you for sharing.

**Comment by phuocng** [comment]
Here it is https://phuoc.ng/collection/this-vs-that/react-create-element-vs-jsx/
